/* C++ static constructor and destructor lists */
/* This is generated by munch.pl, do not edit! */

#include <vxWorks.h>

/* Declarations */
extern void _GLOBAL_$I$_$_18epicsThreadRunable(void);
extern void _GLOBAL_$I$_$_21epicsTimerQueueActive(void);
extern void _GLOBAL_$I$_$_7noopiiu(void);
extern void _GLOBAL_$I$__13localHostName(void);
extern void _GLOBAL_$I$__14repeaterClientRC11osiSockAddr(void);
extern void _GLOBAL_$I$contextCreate__9dbServiceR10epicsMutexT1R16cacContextNotify(void);
extern void _GLOBAL_$I$energy_calc_registerRecordDeviceDriver(void);
extern void _GLOBAL_$I$epicsNAN(void);
extern void _GLOBAL_$I$iocshRegister(void);
extern void _GLOBAL_$I$logMsgToErrlog(void);
extern void _GLOBAL_$I$osdNTPGet(void);
extern void _GLOBAL_$D$_$_21epicsTimerQueueActive(void);
extern void _GLOBAL_$D$_$_7noopiiu(void);
extern void _GLOBAL_$D$__13localHostName(void);
extern void _GLOBAL_$D$contextCreate__9dbServiceR10epicsMutexT1R16cacContextNotify(void);

char __dso_handle = 0;

/* List of Constructors */
void (*_ctors[])(void) = {
    _GLOBAL_$I$_$_18epicsThreadRunable,
    _GLOBAL_$I$_$_21epicsTimerQueueActive,
    _GLOBAL_$I$_$_7noopiiu,
    _GLOBAL_$I$__13localHostName,
    _GLOBAL_$I$__14repeaterClientRC11osiSockAddr,
    _GLOBAL_$I$contextCreate__9dbServiceR10epicsMutexT1R16cacContextNotify,
    _GLOBAL_$I$energy_calc_registerRecordDeviceDriver,
    _GLOBAL_$I$epicsNAN,
    _GLOBAL_$I$iocshRegister,
    _GLOBAL_$I$logMsgToErrlog,
    _GLOBAL_$I$osdNTPGet,
    NULL
};

/* List of Destructors */
void (*_dtors[])(void) = {
    _GLOBAL_$D$_$_21epicsTimerQueueActive,
    _GLOBAL_$D$_$_7noopiiu,
    _GLOBAL_$D$__13localHostName,
    _GLOBAL_$D$contextCreate__9dbServiceR10epicsMutexT1R16cacContextNotify,
    NULL
};
