# These are the IOCs we should create. The IOC should either have the same name
# as an xml or py file in etc/makeIocs, or be suffixed with _sim to create a
# simulation from that same file
IOCS := BL46P-EA-IOC-01 BL46P-EA-IOC-02 BL46P-EA-IOC-03 BL46P-MO-IOC-01 
IOCS += BL47P-EA-IOC-01 BL47P-EA-IOC-02 BL47P-MO-IOC-01
IOCS += BL48P-EA-IOC-01 BL48P-EA-IOC-02 BL48P-MO-IOC-01
IOCS += BL49P-EA-IOC-01 BL49P-EA-IOC-02 BL49P-MO-IOC-01

# These are the dirs that each IOC lives in
IOC_DIRS := $(patsubst %, $(TOP)/iocs/%, $(IOCS))
