# This file was automatically generated on Fri 23 Apr 2021 13:44:29 BST from
# source: /home/eja26438/Documents/EPICS_CONTAINERS/bl46p-builder/etc/makeIocs/BL46P-EA-IOC-03.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------


dbLoadDatabase "../../dbd/BL46P-EA-IOC-03.dbd"
BL46P_EA_IOC_03_registerRecordDeviceDriver(pdbbase)

# Final ioc initialisation
# ------------------------
dbLoadRecords '../../db/BL46P-EA-IOC-03_expanded.db'

# Extra IOC commands
echo "test"

iocInit
