#!/bin/sh
# This file was automatically generated on Fri 23 Apr 2021 13:44:29 BST from
# source: /home/eja26438/Documents/EPICS_CONTAINERS/bl46p-builder/etc/makeIocs/BL46P-EA-IOC-03.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi


exec ./BL46P-EA-IOC-03 stBL46P-EA-IOC-03.boot
