/* This file was automatically generated on Fri 23 Apr 2021 10:07:50 BST from
 * source: /home/eja26438/Documents/EPICS_CONTAINERS/bl46p-builder/etc/makeIocs/BL46P-EA-IOC-03.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

